### ISSUE TITLE
Consider dropping reduction rules

### ISSUE THREAD

**Issue by Kha** [ammkrn/nanoda#2]
I've had a quick look at where you are constructing thread-shared `Expr`s that are not part of the input, and as far as I can see that happens only in `ReductionRule::new_nondef_rr`. Reduction extensions are a remnant of Lean 2's more extensible kernel; we've since moved to hard-coding all reduction rules: https://github.com/leanprover/lean4/blob/cb1680e096ae49653fb68c1a65d4b5a539f81ca6/src/kernel/type_checker.cpp#L325-L338. I assume this might lead to simpler, more efficient code, and in particular could open up more optimizations regarding reference counting (I could probably work around it, but this seemed like a good change in general).

**Comment by Kha** [comment]
> thread-shared `Expr`s that are not part of the input

Sorry, of course there are a few more such places like constructing the intro and elim rules. I'll have to think harder about how to avoid `Arc`. Anyway, you may or may not still be interested in this change.

**Comment by ammkrn** [comment]
Yeah, definitely. It might take me a little while to work out the details since my knowledge of (and ability to read) C++ is extremely limited, but I'll start working through it. I'm really excited that someone actually working on Lean has taken an interest in this, so if you come across anything else that can be improved or made more in line with Lean 4 please let me know.
As far as the reference counting stuff, Expr terms are only ever used immutably (I'd have to double check I didn't sneak any muts in), so I'm not above declaring unsafe impls of Send/Sync if I can put a reasonable defense for it on paper or find a way to enforce safety at runtime. I think the fact that items constructed outside of Env are thread-local should avoid issues with non-atomic increments/decrements to strong counts.
I had an idea for a much better arena based solution than the last one I tried, so I'm going to put that together as well and see what happens.

**Comment by Kha** [comment]
Yes, arenas could be promising as well. I believe they worked well enough for rustc, though it's not clear to me exactly how much garbage we produce while checking a single declaration.

**Comment by ammkrn** [comment]
That's a good point. It looks like the average number of temporary expressions per TypeChecker is only ~15k for mathlib, but there are a handful of outliers that go through a few million, so I'll wait and see if I can find any spots where there's a lot of reuse going on before moving forward with that.

**Comment by ammkrn** [comment]
I have a draft of this done, but I don't have the inductive part working properly yet. I'm taking the LSAT (an American standardized test) at the end of November and I'll be using all of my spare time to study for it, though I'd much rather work on this. I'll reopen and complete when I'm done, I just don't want this to have been open and unfinished for three months.

**Comment by ammkrn** [comment]
@Kha 

Can you explain maybe in pseudo-code how `name::replace_prefix` (name.cpp line 411) should behave? I'm a little lost in the pointer/m_obj indirection.

**Comment by ammkrn** [comment]
A first draft of this is working on the v0.2.x branch. It checks lean3 export files, the stack overflow issue is gone, and mathlib seems to check significantly faster. I sort of hit a wall in doing the mutual/nested inductive stuff since I just wasn't able to understand the name generation and how `local_ctx` and `FVar` work/interact, so that's not done. `Projection`, `Theorem`, and `Opaque` are also unimplemented as of now and are just checked as `Definition` items; I guess those are going to be their own export items in lean4 (IE #PROJ or something)? The last discrepancy is that I couldn't figure out how lean4 gets away with building the dependent eliminator for all inductives, so I carried over the `use_dep_elim` conditional from the lean3 version.

**Comment by Kha** [comment]
Nice. I'm not too familiar with the kernel code since this is Leo's territory, but if you have a specific question perhaps with an example, I can look into that.
